### ISSUE TITLE
IOS release build failed

### ISSUE THREAD

**Issue by codebymani** [opsway/react-native-paytm#1]
Hi opsway,

It's working great while building in "debug" mode and It was broken for release build. 

Here's the log 
clang: error: no such file or directory: '/Users/Manipalreddy/Library/Developer/Xcode/DerivedData/stuMagz-djwihkiljmwzqehkhdyzqbptwmsp/Build/Products/Release-iphonesimulator/libRNPayTm.a'

I even tried to build by deleting derived data, clean. Is there any work around for release build ?

Xcode: 9.4.1
React Native: 55.4

**Comment by philly25** [comment]
Hi, @codebymani!  

Try these steps to resolve the issue:

1. Important thing when clearing Derived Data is to close Xcode before clearing. So:
- Close Xcode
- To remove both derived data and build, run this command from your project's root directory:
```bash
rm -rf ~/Library/Developer/Xcode/DerivedData && rm -rf ios/build
```
- Open Xcode and try to archive

2. Check if you have SystemConfiguration.framework in the "Link Frameworks and Libraries" section (as described in Step 1 of the [official docs](https://developer.paytm.com/docs/v1/ios-sdk)). If no, then add it. 
3. As suggestion, you can consider upgrading to Xcode 10. It will make your further life easier.

**Comment by codebymani** [comment]
None of them worked. May be I should upgrade to Xcode10.
Thank You @philly25 .

**Comment by codebymani** [comment]
> Hi, @codebymani!
> 
> Try these steps to resolve the issue:
> 
> 1. Important thing when clearing Derived Data is to close Xcode before clearing. So:
> 
> * Close Xcode
> * To remove both derived data and build, run this command from your project's root directory:
> 
> ```shell
> rm -rf ~/Library/Developer/Xcode/DerivedData && rm -rf ios/build
> ```
> 
> * Open Xcode and try to archive
> 
> 1. Check if you have SystemConfiguration.framework in the "Link Frameworks and Libraries" section (as described in Step 1 of the [official docs](https://developer.paytm.com/docs/v1/ios-sdk)). If no, then add it.
> 2. As suggestion, you can consider upgrading to Xcode 10. It will make your further life easier.

Tried all the steps didn't work! I also tried upgrading to Xcode10. Is your SDK bitcode enabled?

**Comment by philly25** [comment]
No, we use BitcodeDisabled SDK.

**Comment by philly25** [comment]
Closed due to inactivity. Feel free to reopen this issue.

**Comment by rv-tech** [comment]
Still getting this error. Any updates on this
