### ISSUE TITLE
Can you please share which SDKs were used from PayTM ?

### ISSUE THREAD

**Issue by sillysachin** [opsway/react-native-paytm#2]
Please share the github binary links for PayTM SDKs.

**Comment by philly25** [comment]
Here is [Paytm_iOS_App_Kit](https://github.com/Paytm-Payments/Paytm_iOS_App_Kit)

We are using [BitCodeDisabled SDK](https://github.com/Paytm-Payments/Paytm_iOS_App_Kit/tree/master/ObjC/BitCodeDisabled)

**Comment by sillysachin** [comment]
Can you also share Android SDK used?

**Comment by philly25** [comment]
com.paytm:pgplussdk:1.1.5

**Comment by philly25** [comment]
If you have any other questions regarding SDK - feel free to reopen this issue.
