### ISSUE TITLE
Release build error on iOS

### ISSUE THREAD

**Issue by rv-tech** [opsway/react-native-paytm#3]
It is working fine in debug mode, but giving the following error in release mode

clang: error: no such file or directory: '/Users/user/Library/Developer/Xcode/DerivedData/VIP-dmfyltthdikhvqftzkkrbhlfsdpe/Build/Intermediates.noindex/ArchiveIntermediates/VIP/BuildProductsPath/Release-iphoneos/libRNPayTm.a'

**Comment by philly25** [comment]
1. Have you tried to clean DerivedData and Build as described in this [comment](https://github.com/opsway/react-native-paytm/issues/1#issuecomment-468357711)?
2. What is your Xcode version?

**Comment by philly25** [comment]
Closed due to inactivity.
