### ISSUE TITLE
Android build error, help

### ISSUE THREAD

**Issue by karanpratapsingh** [opsway/react-native-paytm#4]
Hey, first of all thanks for updating this module...it's working fine in ios debug right now but on android it is giving this error:

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithDexMergerForDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
  The number of method references in a .dex file cannot exceed 64K.
  Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html

**Comment by karanpratapsingh** [comment]
Here's the solution:

add the following in app/build.gradle under default config:

 multiDexEnabled true // multi dex resolution support for paytm sdk

**Comment by philly25** [comment]
Yes, this is multidex related issue, and you solved it just right.
