### ISSUE TITLE
How to know if payment succeeds?

### ISSUE THREAD

**Issue by karanpratapsingh** [opsway/react-native-paytm#5]
Right now after the payment is complete...It just shows a blank white screen, how can I know if it has succeeded or failed?

Thanks

**Comment by philly25** [comment]
In usage example you should use onPayTmResponse method to handle PayTM response. On Android you should check property STATUS, if it's 'TXN_SUCCESS', then transaction succeed.

```
onPayTmResponse = (resp) => {
    const {STATUS, status, response} = resp;

    if (Platform.OS === 'ios') {
      if (status === 'Success') {
        const jsonResponse = JSON.parse(response);
        const {STATUS} = jsonResponse;

        if (STATUS && STATUS === 'TXN_SUCCESS') {
          // Payment succeed!
        }
      }
    } else {
      if (STATUS && STATUS === 'TXN_SUCCESS') {
        // Payment succeed!
      }
    }
  };

```

**Comment by philly25** [comment]
this response comes from [Transaction Status API](https://developer.paytm.com/docs/transaction-status-api) request. This is the last step of the [PayTm flow](https://developer.paytm.com/docs/v1/android-sdk/).

**Comment by karanpratapsingh** [comment]
Thanks
