### ISSUE TITLE
Getting a popup and then the popup closes in IOS

### ISSUE THREAD

**Issue by Sukumar-Abhijeet** [opsway/react-native-paytm#6]
I am getting a popup like thing in the app then the popup closes  in IOS , 
WHy is this happening >>?

**Comment by philly25** [comment]
Could you please specify conditions when this popup appears in your app? And screenshot would be useful as well.

**Comment by philly25** [comment]
Closed due to inactivity

**Comment by FaisalAli19** [comment]
Hi,

I am also facing this issue. Right after `Paytm.startPayment(details)` a white popup comes and closes.

It's hard to take a screenshot as this happens for the split seconds. I think that white popup is the screen where the user needs to log in and confirm the payment.

**Comment by FaisalAli19** [comment]
Sorry, my mistake.
It was happening as the value of TXN_AMOUNT was in the number format it should be String.

**Comment by philly25** [comment]
Good to know you've figured it out, and thanks @FaisalAli19 for posting it for others.

**Comment by rishabh8456** [comment]
I have same issue.PopUp comes & close.
CALLBACK_URL: "https://securegw.paytm.in/theia/paytmCallback?ORDER_ID=PTCA62637083982241804253"
CHANNEL_ID: "WAP"
CUST_ID: "PTCA62"
EMAIL: "ptc.sachin@gmail.com"
INDUSTRY_TYPE_ID: "Retail104"
MID: "Ptccir44733303573831"
MOBILE_NO: "9355522262"
ORDER_ID: "PTCA62637083982241804253"
Status: "Success"
TXN_AMOUNT: "3000"
WEBSITE: "APPPROD"
checksumFinal: "rbpG/G0ZeTXfOGduMnejWnIID0BJJCbjbWW+7O04FQi4AiwqiokGMpzLbR8/M+0Ur6cLDLUygObv7WDe9Ce63iChdjkNLMhcXcxW7A1wI8s="
i have this object.
I have facing this issue in react native ios

**Comment by FaisalAli19** [comment]
@rishabh8456 
Please remove status and check. It should solve the issue. As in Paytm API status is not the params.

**Comment by rishabh8456** [comment]
@FaisalAli19 
 mode: 'Production', // 'Staging' or 'Production'
      MID: paytmConfig.MID,
      INDUSTRY_TYPE_ID: paytmConfig.INDUSTRY_TYPE_ID,
      WEBSITE: paytmConfig.WEBSITE,
      CHANNEL_ID: paytmConfig.CHANNEL_ID,
      TXN_AMOUNT: paytmConfig.amount, // String
      ORDER_ID: paytmConfig.ORDER_ID, // String
      EMAIL: paytmConfig.EMAIL, // String
      MOBILE_NO: paytmConfig.MOBILE_NO, // String
      CUST_ID: paytmConfig.CUST_ID, // String
      CHECKSUMHASH: paytmConfig.checksumFinal, //From your server using PayTM Checksum Utility 
      CALLBACK_URL: paytmConfig.CALLBACK_URL,
this is my object that i set for payment

**Comment by FaisalAli19** [comment]
@rishabh8456 
Can you share the code.
As the above object seems correct except Channel_id: wap which is missing.

**Comment by rishabh8456** [comment]
@FaisalAli19 CALLBACK_URL: "https://securegw.paytm.in/theia/paytmCallback?ORDER_ID=PTCA62637085850660185023"
CHANNEL_ID: "WAP"
CUST_ID: "PTCA62"
EMAIL: "ptc.sachin@gmail.com"
INDUSTRY_TYPE_ID: "Retail104"
MID: "Ptccir44733303573831"
MOBILE_NO: "9355522262"
ORDER_ID: "PTCA62637085850660185023"
Status: "Success"
TXN_AMOUNT: "3000"
WEBSITE: "APPPROD"
checksumFinal: "zT7DwRX1QTBx8HQ8ePZLPol91Ruua3lJVZsFWpynHcFxznMgXRbVyE4YbzeMgBfb1f7/b1CxsI0h2wxNWq7rND/c3Zc1iBf9+q4LW27Mcpg="

**Comment by rishabh8456** [comment]
@FaisalAli19 
callBackPaytm(paytmConfig) {
    const details = {
      mode: 'Production', // 'Staging' or 'Production'
      MID: paytmConfig.MID,
      INDUSTRY_TYPE_ID: paytmConfig.INDUSTRY_TYPE_ID,
      WEBSITE: paytmConfig.WEBSITE,
      CHANNEL_ID: paytmConfig.CHANNEL_ID,
      TXN_AMOUNT: paytmConfig.amount, // String
      ORDER_ID: paytmConfig.ORDER_ID, // String
      EMAIL: paytmConfig.EMAIL, // String
      MOBILE_NO: paytmConfig.MOBILE_NO, // String
      CUST_ID: paytmConfig.CUST_ID, // String
      CHECKSUMHASH: paytmConfig.checksumFinal, //From your server using PayTM Checksum Utility 
      CALLBACK_URL: paytmConfig.CALLBACK_URL,
    };

    Paytm.startPayment(details);
  }
