### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by FaisalAli19** [opsway/react-native-paytm#7]
Hey,

Thanks for the awesome package.

I am getting the below error for iOS when I am linking using cocopods. 

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_PGMerchantConfiguration", referenced from:
      objc-class-ref in libRNPayTm.a(RNPayTm.o)
  "_OBJC_CLASS_$_PGOrder", referenced from:
      objc-class-ref in libRNPayTm.a(RNPayTm.o)
  "_OBJC_CLASS_$_PGTransactionViewController", referenced from:
      objc-class-ref in libRNPayTm.a(RNPayTm.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
And this error after manual linking.

`react/rctbridgemodule.h' file not found`

react-native: 0.60.0
@philly25/react-native-paytm: 1.0.11
Xcode: 10.3

Thanks.

**Comment by ghost** [comment]
I am having this same issue

**Comment by philly25** [comment]
Sorry, but current version is not ready for RN 0.60.0
Soon we're going to add support for the latest RN version. 
Stay tuned!
